### ISSUE TITLE
Add Just Dance 2018 Wii Banner and icon

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [cucholix/wiivc-bis#113]
I have Just Dance 2018 banner and icon made by my friend
[SE8P.zip](https://github.com/cucholix/wiivc-bis/files/11645954/SE8P.zip)

**Comment by cucholix** [comment]
Please create a pull request

**Comment by TheEpicNoobZilla** [comment]
I hope i did this right, it's my first PR
