### ISSUE TITLE
NES VC Banner Template has Released: and Players: 1 hard embedded ;)

### ISSUE THREAD

**Issue by kevintosh** [cucholix/wiivc-bis#117]
I do not have the original file so I cannot remove it, maybe you still can?

(trust me, I have tried disabling layers, other consoles seem fine)

![Screenshot 2023-07-20 at 3 43 44 PM](https://github.com/cucholix/wiivc-bis/assets/715643/4dcd3b34-5109-4dae-b99f-a868cae22554)

Famicom:

![Screenshot 2023-07-20 at 3 44 33 PM](https://github.com/cucholix/wiivc-bis/assets/715643/0b9bda9e-a57f-4940-a531-74145d391913)

**Comment by cucholix** [comment]
[d5e23bfb3697a87ce6d749d2d6be6ae4c39b32e8](https://github.com/cucholix/wiivc-bis/commit/d5e23bfb3697a87ce6d749d2d6be6ae4c39b32e8) fixed, thanks for pointing out.

**Comment by cucholix** [comment]
Fixed

**Comment by kevintosh** [comment]
> [d5e23bfb3697a87ce6d749d2d6be6ae4c39b32e8](https://github.com/cucholix/wiivc-bis/commit/d5e23bfb3697a87ce6d749d2d6be6ae4c39b32e8) fixed, thanks for pointing out.

Hey! Thanks to YOU, man! ;) I'm but just a mere user of this amazing stuff.
