### ISSUE TITLE
VCiicon

### ISSUE THREAD

**Issue by larsenv** [cucholix/wiivc-bis#17]
I made a tool called "[VCiicon](https://github.com/larsenv/VCiicon)" a long time ago and the goal was to make a bash script and have the banner text whited out. Not everything was whited out (and I couldn't find a picture of the consoles Nintendo used for the banner so I could recreate it). The DS one was recreated though.

Anyway, just thought you wanted to check it out. The project ended up being a failure because people started using their own art as the banner, and it annoyed me. This is off-topic, but I was also annoyed when I was trying to get eShop covers at [GameTDB](http://gametdb.com). People were making bad Wii U covers with different templates and stretched the covers out to a canvas, and it looked so bad and people were loving it. The way injects and covers were done for Wii was pretty good, but Wii U not so much.

**Comment by cucholix** [comment]
I'm not quite sure what it does yet, if I understand correct from your github it resize the title screen for it match with the banner transparent window?

Still have to install cygwin in my Windows, although you have planned a Windows bat no?

**Comment by larsenv** [comment]
@cucholix It was a little tool to take a screenshot of a game, resize it, put it on the banner, and make an icon as well.

I never bothered finishing it, some of the code is repeated in the main script. It's not a good script and not very flexible. One of the goals was to remove all the text from the banner to make a nice template [(this was the best template I made)](https://github.com/larsenv/VCiicon/blob/master/resources/bootTvTex-DS.png), but if someone wants to remove the text from the other banners that's cool.

I'll make a PR to add the templates to your repo.

**Comment by larsenv** [comment]
@cucholix Actually I took a look at the Virtual Console template that's in the repository, it's what I was trying to do with the program. Never mind then.
