### ISSUE TITLE
Add custom Wii title "Newer Super Mario Bros. Wii" images.

### ISSUE THREAD

**Issue by Maciu1** [cucholix/wiivc-bis#54]
Newer Super Mario Bros. Wii (EU) [SMNP03]
iconTex.png 
![icontex](https://user-images.githubusercontent.com/34245941/33564880-f2e92020-d91b-11e7-85f0-b59cc98a5798.png)

bootTvTex.png
![boottvtex](https://user-images.githubusercontent.com/34245941/33564894-fc9d28b4-d91b-11e7-94a6-fdfdd40b1c0f.png)

It works. I tested it myself.

**Comment by cucholix** [comment]
Thanks, icon logo looks vertical stretched though.

**Comment by Maciu1** [comment]
I found this one here:
https://gbatemp.net/threads/banners-icon-templates-for-wii-vc.483080/page-14
I think it looks better.
![icontex](https://user-images.githubusercontent.com/34245941/33576447-2992c184-d940-11e7-85bf-be9573a12719.png)

**Comment by cucholix** [comment]
Yep, make a pull request with the "New" logo only and I will upload it
