### ISSUE TITLE
Sonic Riders (GXEE8P)

### ISSUE THREAD

**Issue by WayneMario** [cucholix/wiivc-bis#77]
One of the images for this game is for Sonic Adventure DX and not Sonic Riders.
The bootTvTex image.

**Comment by gilramot** [comment]
Can somebody close this issue? [Fixed](https://github.com/cucholix/wiivc-bis/commit/106f50630605792018d8b0b4bc700b8dd56fe6e3)
@cucholix

**Comment by gilramot** [comment]
Can somebody close this issue? [Fixed](https://github.com/cucholix/wiivc-bis/commit/f7f0893e017b286806a0574d444a753116e0edd6)
@cucholix
