### ISSUE TITLE
wii sports + wii sports resort

### ISSUE THREAD

**Issue by Seperat** [cucholix/wiivc-bis#92]
i noticed that there is wii sports, i don't know about wii sports resort as of 3/22/2021, but there isn't wii sports + wii sports resort. the id is SP2E01 if that is important.

**Comment by gilramot** [comment]
Can somebody close this issue? [Fixed](https://github.com/cucholix/wiivc-bis/commit/f7f0893e017b286806a0574d444a753116e0edd6)
@cucholix
