### ISSUE TITLE
Custom cover for Lego Star Wars Complete Saga

### ISSUE THREAD

**Issue by bestKomrad** [cucholix/wiivc-bis#93]
![iconTex](https://user-images.githubusercontent.com/24728952/116111775-a1e47380-a6bf-11eb-8abf-5f33d05bb91e.png)
![bootTvTex](https://user-images.githubusercontent.com/24728952/116111779-a315a080-a6bf-11eb-8fcb-c02b404589a3.png)
Custom cover for Lego Star Wars Complete Saga ( RLGP / 524C4750 )

**Comment by cucholix** [comment]
Please add via pull request

**Comment by sergiosaint** [comment]
this is in folder RLGP64 should it be duplicated or moved into RLGE64 ?

(I dont know if there is a way to make diferent regions to point to the same images)

**Comment by gilramot** [comment]
Can somebody close this issue? [Fixed](https://github.com/cucholix/wiivc-bis/pull/96/commits/6bd9b37caecdef3afdb123fa80221def66f36ad6)
@cucholix
